name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dbt_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'